import type { Metadata } from "next";
import { Geist, Geist_Mono, Red_Hat_Text } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";
import Header from "@/components/Header";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const redHatText = Red_Hat_Text({
  subsets: ["latin"], // Sous-ensemble pour les caractères latins
  weight: ["400", "600", "700"], // Poids : normal, semi-bold, bold (ajustez selon vos besoins)
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${redHatText.className} antialiased p-4`}>
        <Header />
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
